name: Custom action
description: A custom action
inputs:
  GITHUB_TOKEN:
    description: A GitHub token to execute GitHub tasks
    required: true
  GITHUB_REF:
    description: The branch or tag ref that triggered the workflow
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
