name: Comment on Issue
on:
  issues:
    types: [opened, labeled]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/comment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
