name: Deploy Preview
on: pull_request
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: ./.github/actions/custom-action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
