name: Issue
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/issue
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
