name: Ready for review
on:
  pull_request:
    types: [opened, ready_for_review, reopened]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/labeler
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
