name: Reviewer
on: pull_request_review
jobs:
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/reviewer
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTO_LABEL_USERS: ['joshblack']
