name: Issue
description: A custom action
inputs:
  GITHUB_TOKEN:
    description: A GitHub token to execute GitHub tasks
    required: true
  enabled:
    description: Specify whether this action should run
runs:
  using: 'docker'
  image: 'Dockerfile'
